fueltracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'fueltracker.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^mpg/', include('mpg.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

mpg/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^model/(?P<model_name>[a-zA-Z0-9]+)$', views.model, name='model'),
  url(r'^make/(?P<make_name>[a-zA-Z]+)$', views.make, name='make'),
  url(r'^vehicle/(?P<vehicle_id>[0-9]+)$', views.vehicle, name='vehicle'),
  url(r'^login_user$', views.login_user, name='login_user'),
  url(r'^logout_user$', views.logout_user, name='logout_user'),
  url(r'^register$', views.register, name='register'),
  url(r'^register_page$', views.register_page, name='register_page'),
  url(r'^addMake$', views.addMake, name='addMake'),
]

mpg/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Class for MPG Users
class MpgUser(models.Model):
  user = models.ForeignKey(User)
  
  def __str__(self):
    return self.user.username

# Class for Makes of vehicles
class Make(models.Model):
  name = models.CharField(max_length=20)

  def __str__(self):
    return self.name

# Class for Models of vehicles
class Model(models.Model):
  make = models.ForeignKey(Make)
  name = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  # Calculates the average MPG for all vehicles of this model
  def average_mpg(self):
    # get all the vehicles of this model
    vehicles = self.vehicle_set.all()
    
    # gather all the fuel ups
    fuel_ups = []
    for vehicle in vehicles:
      fuel_ups.extend(vehicle.fuelup_set.all())

    # if no fuel ups, return 0
    if not fuel_ups:
      return 0

    # calculate and return the average MPG
    return sum([fu.miles for fu in fuel_ups]) / sum([fu.gallons for fu in fuel_ups])

# Class for Vehicles
class Vehicle(models.Model):
  owner = models.ForeignKey(MpgUser)
  model = models.ForeignKey(Model)
  year = models.IntegerField()
  name = models.CharField(max_length=20)

  def __str__(self):
    return self.name

# Class for FuelUps
class FuelUp(models.Model):
  date = models.DateField()
  miles = models.IntegerField(default = 0)
  gallons = models.FloatField()
  cost = models.FloatField()
  vehicle = models.ForeignKey(Vehicle)

  def __str__(self):
    return "%.2f gal at $%.2f: %.1f MPG" % (self.gallons, self.cost, self.miles / self.gallons)

  def mpg(self):
    return self.miles / self.gallons

mpg/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.core.urlresolvers import reverse

from .models import MpgUser, Make, Model, Vehicle, FuelUp

# Create your views here.

# Convenience function to get the current user
def get_user(request):
  # Check if user is authenticated
  if request.user.is_authenticated():
    # if so, return the user
    user = request.user
  else:
    # otherwise, return None
    user = None
    
  return user
  
# View to handle user authentication
def login_user(request):
  # get username and password
  username = request.POST['username']
  password = request.POST['password']

  # authenticate the user
  user = authenticate(username=username, password=password)

  # check that user was authenticated properly
  if user is not None:
    if user.is_active:
      # if so, log them in
      login(request, user)

  # TODO handle authentication errors

  # redirect to the index
  return HttpResponseRedirect(reverse('index'))
  
# View to handle logging out users
def logout_user(request):
  # logout the user
  logout(request)
  
  # redirect to the index
  return HttpResponseRedirect(reverse('index'))

# Simple view to show the register page
def register_page(request):
  return render(request, 'mpg/register.html')

# View to handle registering users
def register(request):
  # Get the user information
  username = request.POST['username']
  email = request.POST['email']
  password = request.POST['password']

  # Create the user
  user = User.objects.create_user(username, email, password)
  
  # Create and save the MPG user
  mpg_user = MpgUser()
  mpg_user.user = user
  mpg_user.save()
  
  # Authenticate the user
  user = authenticate(username=username, password=password)

  # Check that user was authenticated properly
  if user is not None:
    if user.is_active:
      # if so, log them in
      login(request, user)

  # redirect to the index
  return HttpResponseRedirect(reverse('index'))

# Index view
def index(request):
  # Get the user
  user = get_user(request)
  
  # Set the context, retrieving all makes
  context = {'user':user, 'makes':Make.objects.all()}
  return render(request, 'mpg/index.html', context)

# Make view
def make(request, make_name):
  # get the user
  user = get_user(request)
  
  # get the make by name
  make = Make.objects.get(name__exact=make_name)
  
  # set the context and render the page
  context = {'user':user, 'make':make}
  return render(request, 'mpg/make.html', context)


# Model view
def model(request, model_name):
  # Get the user
  user = get_user(request)
  
  # Get the model based on the name
  model = Model.objects.get(name__exact=model_name)
  
  # Set the context and render the page
  context = {'user':user, 'model':model}
  return render(request, 'mpg/model.html', context)


# Vehicle view
def vehicle(request, vehicle_id):
  # get the user
  user = get_user(request)
  
  # get the vehicle by ID or 404
  vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
  
  # set the context and render the page
  context = {'user':user,'vehicle':vehicle}
  return render(request, 'mpg/vehicle.html', context)

# View to add a new make
# TODO this will become part of the API
def addMake(request):
  # get the name of the new make
  make_name = request.POST['make']
  
  # if a make does not already exist by that name
  if not len(Make.objects.filter(name=make_name)):
    # create and save the new make
    make = Make()
    make.name = make_name
    make.save()
    
  

authy/templates/authy/index.html
<h3>Sign Up</h3>

<form action="{% url 'signup' %}" method="POST">

  {% csrf_token %}
  <input type="text" placeholder="Username" name="username"/><br />
  <input type="password" placeholder="Password" name="password" /><br />
  <input type="submimt" value="Submit" /> 
</form>

mpg/templates/mpg/includes/user_login.html
{% if user %}

<form style="display:inline" action="{% url 'logout_user' %}">
  <b>Hi {{ user.username }}!</b>
  <input type="submit" value="Logout"/>
</form>

{% else %}

<form action="{% url 'login_user' %}" method="POST">

  {% csrf_token %}
  
  <input type="text" placeholder="Username" name="username"/><br />
  <input type="password" placeholder="Password" name="password" /><br />
  <input type="submit" value="Login" />
</form>

<form action="{% url 'register_page' %}">
  <input type="submit" value="Register"/>
</form>

{% endif %}

mpg/templates/mpg/index.html
{% include "mpg/includes/user_login.html" %}

{% for make in makes %}
<h3><a href="{% url 'make' make.name %}">{{ make.name }}</a></h3>
<ul>
  {% for model in make.model_set.all %}
  <li><a href="{% url 'model'  model.name %}">{{ model.name }}</a></li>
  {% endfor %}
</ul>
{% endfor %}

<h4>Add a Make</h4>
<form action="{% url 'addMake' %}" method="post">
  {% csrf_token %}
  <label for="make">New Make</label>
  <input type="text" name="make" id="make"/>
  <input type="submit" value="Add"/>
</form>

mpg/templates/mpg/make.html
{% load humanize %}

{% include "mpg/includes/user_login.html" %}

<h3><a href="/mpg">All</a> > {{ make.name }}</h3>
<ul>
  {% for model in make.model_set.all %}
  <li><a href="/mpg/model/{{ model.name }}">{{ model.name }}</a> -- {{ model.average_mpg|floatformat:2 }} mpg</li>
  {% endfor %}
</ul>

mpg/templates/mpg/model.html
{% include "mpg/includes/user_login.html" %}

<h3><a href="/mpg">All</a> > <a href="/mpg/make/{{ model.make.name }}">{{ model.make.name}}</a> > {{ model.name }}</h3>
<ul>
  {% for vehicle in model.vehicle_set.all %}
  <li><a href="/mpg/vehicle/{{ vehicle.id }}">{{ vehicle.name }}</a></li>
  {% endfor %}
</ul>

mpg/templates/mpg/register.html
<h3>Sign Up</h3>

<form action="{% url 'register' %}" method="POST">

  {% csrf_token %}
  
  <input type="email" placeholder="Email" name="email" /><br />
  <input type="text" placeholder="Username" name="username"/><br />
  <input type="password" placeholder="Password" name="password" /><br />
  <input type="submit" value="Submit" />
</form>

mpg/templates/mpg/vehicle.html
<h3>
    <a href="/mpg">All</a> > 
    <a href="/mpg/make/{{ vehicle.model.make.name }}">{{ vehicle.model.make.name}}</a> > 
    <a href="/mpg/model/{{ vehicle.model.name }}">{{ vehicle.model.name }}</a>
</h3>
<h4>{{ vehicle.name }}</h4>
<ul>
  {% for fuelup in vehicle.fuelup_set.all %}
  <li>{{ fuelup.date }} -- {{ fuelup.miles }} -- {{ fuelup.mpg }} mpg</li>
  {% endfor %}
</ul>